version: "2"
services:
  nginx01:
    image: techwithnc/nginx:3.0
    ports:
      - 80:80
    networks:
      net01:
        ipv4_address: "192.168.66.101"
  busybox01:
    build: .
    networks:
      net01:
        ipv4_address: "192.168.66.102"
networks:
  net01:
    ipam:
      driver: default
      config:
        - subnet: "192.168.66.0/24"
